namespace MemorySystem.Application.AccessAuditing;

public sealed record AccessAuditEventRecord(
    Guid Id,
    string ActionType,
    string Outcome,
    Guid? ActorPrincipalId,
    Guid? TargetPrincipalId,
    string? PrincipalType,
    string? AuthMethod,
    string? CredentialId,
    Guid? IdentityBindingId,
    string? ScopeType,
    string? ScopeId,
    string? RoleId,
    string? NamespacePrefix,
    string? Permission,
    string? ResourceType,
    string? ResourceId,
    string? ReasonCode,
    string? RequestMethod,
    string? RequestPath,
    string? CorrelationId,
    IReadOnlyDictionary<string, string?> Metadata,
    DateTimeOffset OccurredAt);
